# Job profile

In [6]:
import json

with open("jd_structured.json", "r") as f:
    jd_structured = json.load(f)

In [ ]:
job_profile=str(json.dumps(jd_structured, indent=2))

In [56]:
print(job_profile)

{
  "role_title": "Senior AI Engineer \u2014 Founding Team",
  "role_category": "Applied ML / Information Retrieval / Search & Recommendation",
  "experience": {
    "min_years": 5,
    "max_years": 9
  },
  "core_problem": [
    "The current candidate matching/search system relies on brittle, low-leverage BM25 and rule-based scoring.",
    "The company needs to quickly design, deploy, and scale a high-leverage v2 hybrid search and ranking engine that directly impacts user engagement.",
    "Lack of evaluation infrastructure (A/B testing, offline benchmarks, feedback loops) makes it impossible to systematically improve search relevance without flying blind."
  ],
  "must_have_skills": [
    "Production experience with embedding-based retrieval models (sentence-transformers, BGE, E5, etc.)",
    "Production management of vector databases or hybrid search index lifecycle (index refresh, handling drift, quality regression)",
    "Strong, production-grade Python coding skills",
    "Rigorous knowledge of ranking evaluation metrics (NDCG, MRR, MAP, offline-to-online correlation)"
  ],
  "nice_to_have_skills": [
    "LLM fine-tuning methodologies (LoRA, QLoRA, PEFT)",
    "Learning-to-Rank (LTR) model implementation (XGBoost, LambdaMART, neural ranking)",
    "Experience with distributed systems and large-scale model inference optimization",
    "Open-source contributions to AI/ML or search projects"
  ],
  "required_domains": [
    "Information Retrieval (IR)",
    "Search & Recommendation Systems",
    "Natural Language Processing (NLP)",
    "Marketplace / Matchmaking Systems"
  ],
  "required_systems_experience": [
    "Vector Databases (Pinecone, Weaviate, Qdrant, Milvus, FAISS)",
    "Hybrid Search Engines (Elasticsearch, OpenSearch)",
    "Offline evaluation frameworks and online A/B testing infrastructure"
  ],
  "behavioral_requirements": [
    "Pragmatic, 'shipper' mindset over academic or theoretical purity",
    "High autonomy and comfortable with high ambiguity (Series A founding environment)",
    "Strong async communication skills with a heavy emphasis on written documentation",
    "Comfortable with open, direct intellectual debate and rapid decision-making cycles"
  ],
  "hidden_requirements": [
    "Ability to work completely independently without an army of platform or infra engineers to deploy your models",
    "Long-term retention alignment: looking for high-ownership individuals who want equity upside and plan to stay 3+ years, not title-chasers",
    "An intuitive grasp of recruitment or HR-tech search challenges (e.g., matching unstructured resume data with unstructured job descriptions)"
  ],
  "negative_signals": [
    "Frequent job hopping (switching companies every 1-1.5 years to climb titles)",
    "Over-reliance on high-level orchestration frameworks like LangChain/LlamaIndex for basic tasks",
    "Lack of public-facing code, open-source work, or papers if coming from closed-source backgrounds",
    "Reluctance to write production-ready code (e.g., claiming to be an 'architect' or 'tech lead' who no longer codes)"
  ],
  "disqualifiers": [
    "Career spent entirely in pure research/academic environments with zero production deployments",
    "No pre-LLM era ML experience, or AI experience limited strictly to calling wrapper APIs (e.g., OpenAI API) for <12 months",
    "No production code written in the past 18 months",
    "Entire career spent at IT consulting/outsourcing firms (TCS, Infosys, Wipro, Accenture, Cognizant, etc.) without product-company experience",
    "Primary expertise is purely in Computer Vision, Audio, or Robotics with no NLP/Search background"
  ],
  "preferred_candidate_archetypes": [
    {
      "name": "The Product-Minded ML Shipper",
      "description": "An engineer currently working at a fast-growing B2B/B2C marketplace or SaaS startup who has successfully built and deployed a search, match, or recommendation feed from scratch, prioritizing metrics and execution speed over academic perfection."
    }
  ],
  "bad_candidate_archetypes": [
    {
      "name": "The Framework Wrapper Hype-Rider",
      "description": "An engineer whose resume is packed with trendy AI keywords, LangChain tutorials, and Toy GPT wrappers, but lacks foundational software engineering, mathematical intuition for retrieval, or classic IR evaluation metrics."
    },
    {
      "name": "The Pure Research Academic",
      "description": "A researcher with a deep publication record in top AI conferences who is used to working on static datasets with infinite training time, but struggles to write clean production Python or optimize latency."
    },
    {
      "name": "The Enterprise Consulting Engineer",
      "description": "An engineer with a career built inside giant IT services systems who expects highly structured task tickets, clear requirements, and deep organizational hierarchy, rather than chaotic, fast-paced startup execution."
    }
  ],
  "must_have_evidence": [
    "A clear history of owning a production-scale ranking, search, or recommendation system at a product-first company",
    "Demonstrated ability to write and ship clean, complex Python backend/ML code within the last year",
    "Verifiable understanding of how they measured the business/relevance impact of their models (e.g., A/B test results, NDCG improvements)"
  ],
  "location_requirements": "Pune or Noida preferred (hybrid cadence), open to relocation from Tier-1 Indian cities (Delhi NCR, Bangalore, Hyderabad, Mumbai). No visa sponsorship.",
  "what_the_jd_really_means": [
    "'We'd rather you tilt slightly toward shipper than toward researcher' -> Do not waste time building an overly complex model when a simple, hybrid heuristics-and-embeddings approach can be shipped in 5 days to solve the user's immediate pain.",
    "'We are growing the team from 4 to 12' -> You will need to wear many hats: writing code, designing systems, and mentoring junior hires simultaneously.",
    "'We work async-first and write a lot' -> If you cannot clearly articulate your architectural decisions in written design docs, you will not survive our remote/async culture."
  ],
  "evidence_strength": {
    "built_production_ranking_system": 100,
    "built_recommendation_system": 95,
    "owned_search_platform": 95,
    "production_retrieval_system": 90,
    "production_ml_system": 80,
    "relevant_job_title": 75,
    "open_source_contributions": 70,
    "published_paper": 60,
    "side_project": 40,
    "listed_skill": 20,
    "course_or_certificate": 10
  },
  "scoring_dimensions": [
    {
      "name": "Production Ranking & Retrieval Experience",
      "weight": 0.35,
      "reason": "The absolute core of the role is owning the matching/ranking architecture. Theoretical knowledge is useless; they must have managed production retrieval systems, index lifecycles, and embedding drift."
    },
    {
      "name": "Production-Grade Coding & Architecture (Python)",
      "weight": 0.25,
      "reason": "This is a founding team role that writes code daily. We disqualify architects who don't code and researchers who write dirty notebooks. Code quality and system architecture are vital."
    },
    {
      "name": "Evaluation Rigor & Metrics",
      "weight": 0.2,
      "reason": "If the candidate cannot scientifically evaluate if their model is actually better using NDCG, MRR, or online A/B testing, they will keep shipping blind changes."
    },
    {
      "name": "Product Startup Shipper Mindset",
      "weight": 0.2,
      "reason": "Prefers shipping pragmatic, working rankers quickly rather than spending 6 months optimizing a marginal accuracy increase. Disqualifies slow-moving corporate or purely academic profiles."
    }
  ],
  "ideal_candidate_summary": "A highly pragmatic Senior Applied ML / Search Engineer with 5 to 9 years of experience, currently working at a fast-paced product company or marketplace startup. They have hands-on experience building, scaling, and validating hybrid search and recommendation algorithms from scratch using vector databases and ranking metrics (NDCG/MRR). They are active IC coders in Python, communicate exceptionally well in writing, bias strongly toward execution speed over research perfection, and are located in or ready to relocate to Pune/Noida."
}

# IRA VORA PROFILE BUILDING

In [8]:
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# Load JSONL file
df = pd.read_json(
    "/Users/sachisingh/Downloads/so/India_runs_data_and_ai_challenge/candidates.json",
    lines=True
)

# Flatten nested dictionaries
final_df = pd.json_normalize(df.to_dict(orient="records"))

# Show normal rows/columns view
display(final_df.head(1))

,candidate_id,career_history,education,skills,certifications,languages,profile.anonymized_name,profile.headline,profile.summary,profile.location,profile.country,profile.years_of_experience,profile.current_title,profile.current_company,profile.current_company_size,profile.current_industry,redrob_signals.profile_completeness_score,redrob_signals.signup_date,redrob_signals.last_active_date,redrob_signals.open_to_work_flag,redrob_signals.profile_views_received_30d,redrob_signals.applications_submitted_30d,redrob_signals.recruiter_response_rate,redrob_signals.avg_response_time_hours,redrob_signals.skill_assessment_scores.NLP,redrob_signals.skill_assessment_scores.Image Classification,redrob_signals.skill_assessment_scores.Fine-tuning LLMs,redrob_signals.skill_assessment_scores.Speech Recognition,redrob_signals.connection_count,redrob_signals.endorsements_received,redrob_signals.notice_period_days,redrob_signals.expected_salary_range_inr_lpa.min,redrob_signals.expected_salary_range_inr_lpa.max,redrob_signals.preferred_work_mode,redrob_signals.willing_to_relocate,redrob_signals.github_activity_score,redrob_signals.search_appearance_30d,redrob_signals.saved_by_recruiters_30d,redrob_signals.interview_completion_rate,redrob_signals.offer_acceptance_rate,redrob_signals.verified_email,redrob_signals.verified_phone,redrob_signals.linkedin_connected,redrob_signals.skill_assessment_scores.GANs,redrob_signals.skill_assessment_scores.OpenCV,redrob_signals.skill_assessment_scores.Prompt Engineering,redrob_signals.skill_assessment_scores.Object Detection,redrob_signals.skill_assessment_scores.Recommendation Systems,redrob_signals.skill_assessment_scores.FAISS,redrob_signals.skill_assessment_scores.Weights & Biases,redrob_signals.skill_assessment_scores.Forecasting,redrob_signals.skill_assessment_scores.LangChain,redrob_signals.skill_assessment_scores.YOLO,redrob_signals.skill_assessment_scores.PEFT,redrob_signals.skill_assessment_scores.Data Science,redrob_signals.skill_assessment_scores.MLflow,redrob_signals.skill_assessment_scores.Pinecone,redrob_signals.skill_assessment_scores.Feature Engineering,redrob_signals.skill_assessment_scores.BentoML,redrob_signals.skill_assessment_scores.MLOps,redrob_signals.skill_assessment_scores.Qdrant,redrob_signals.skill_assessment_scores.CNN,redrob_signals.skill_assessment_scores.Kubeflow,redrob_signals.skill_assessment_scores.Machine Learning,redrob_signals.skill_assessment_scores.Reinforcement Learning,redrob_signals.skill_assessment_scores.Sentence Transformers,redrob_signals.skill_assessment_scores.Haystack,redrob_signals.skill_assessment_scores.Hugging Face Transformers,redrob_signals.skill_assessment_scores.Semantic Search,redrob_signals.skill_assessment_scores.LoRA,redrob_signals.skill_assessment_scores.Diffusion Models,redrob_signals.skill_assessment_scores.Milvus,redrob_signals.skill_assessment_scores.Time Series,redrob_signals.skill_assessment_scores.Statistical Modeling,redrob_signals.skill_assessment_scores.Elasticsearch,redrob_signals.skill_assessment_scores.Information Retrieval,redrob_signals.skill_assessment_scores.Vector Search,redrob_signals.skill_assessment_scores.Learning to Rank,redrob_signals.skill_assessment_scores.ASR,redrob_signals.skill_assessment_scores.TensorFlow,redrob_signals.skill_assessment_scores.LLMs,redrob_signals.skill_assessment_scores.Computer Vision,redrob_signals.skill_assessment_scores.TTS,redrob_signals.skill_assessment_scores.Weaviate,redrob_signals.skill_assessment_scores.RAG,redrob_signals.skill_assessment_scores.Python,redrob_signals.skill_assessment_scores.OpenSearch,redrob_signals.skill_assessment_scores.BM25,redrob_signals.skill_assessment_scores.scikit-learn,redrob_signals.skill_assessment_scores.pgvector,redrob_signals.skill_assessment_scores.Embeddings,redrob_signals.skill_assessment_scores.LlamaIndex,redrob_signals.skill_assessment_scores.PyTorch,redrob_signals.skill_assessment_scores.Deep Learning,redrob_signals.skill_assessment_scores.QLoRA
0,CAND_0000001,"[{'company': 'Mindtree', 'title': 'Backend Eng...",[{'institution': 'Lovely Professional Universi...,"[{'name': 'Tailwind', 'proficiency': 'intermed...",[],"[{'language': 'English', 'proficiency': 'profe...",Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,6.9,Backend Engineer,Mindtree,10001+,IT Services,86.9,2025-10-16,2026-05-20,True,23,2,0.34,177.8,38.8,64.8,41.6,53.7,356,35,60,18.7,36.1,onsite,False,9.2,249,4,0.71,0.58,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
skills_df = df.explode("skills")

skills_flat = pd.json_normalize(skills_df["skills"])

skills_final = pd.concat(
    [skills_df[["candidate_id"]].reset_index(drop=True),
     skills_flat.reset_index(drop=True)],
    axis=1
)


career_df = df.explode("career_history")

career_flat = pd.json_normalize(career_df["career_history"])

career_final = pd.concat(
    [career_df[["candidate_id"]].reset_index(drop=True),
     career_flat.reset_index(drop=True)],
    axis=1
)

In [10]:
profile_flat = pd.json_normalize(df["profile"])

profile_final = pd.concat(
    [
        df[["candidate_id"]].reset_index(drop=True),
        profile_flat.reset_index(drop=True)
    ],
    axis=1
)

display(profile_final.head(1))

,candidate_id,anonymized_name,headline,summary,location,country,years_of_experience,current_title,current_company,current_company_size,current_industry
0,CAND_0000001,Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,6.9,Backend Engineer,Mindtree,10001+,IT Services

In [11]:
candidate1_career_history = career_final[
    career_final["candidate_id"] == "CAND_0000001"
][
    [	"company",	"title",	"start_date",	"end_date",	"duration_months",	"is_current",	"industry",	"company_size",	"description"]
]

display(candidate1_career_history)

,company,title,start_date,end_date,duration_months,is_current,industry,company_size,description
0,Mindtree,Backend Engineer,2024-03-08,None,27,True,IT Services,10001+,Implemented streaming data pipelines on Kafka ...
1,Dunder Mifflin,Analytics Engineer,2019-07-03,2024-01-08,55,False,Paper Products,201-500,Built and maintained data pipelines on Apache ...

In [12]:
candidate1_skills = skills_final[
    skills_final["candidate_id"] == "CAND_0000001"
][
    ["name", "proficiency", "endorsements", "duration_months"]
]

display(candidate1_skills)

                    name   proficiency  endorsements  duration_months
0               Tailwind  intermediate             3               13
1                    NLP      advanced            37               26
2   Image Classification      advanced             7               40
3       Fine-tuning LLMs      advanced            21               36
4       Weights & Biases  intermediate            13               30
5     Speech Recognition      advanced            52               33
6              Photoshop  intermediate             8               24
7                    TTS      advanced            56               60
8                   LoRA  intermediate             0               28
9            Apache Beam  intermediate             4                9
10                   AWS      beginner             5                8
11                 Flask      beginner            15               15
12               BentoML  intermediate             3               36
13                Milvus      advanced            40               35
14                  GANs      advanced            12               19
15  Statistical Modeling  intermediate             9                8
16                   GCP      beginner             7                2

In [13]:
education_df = df.explode("education")

education_flat = pd.json_normalize(education_df["education"])

education_final = pd.concat(
    [
        education_df[["candidate_id"]].reset_index(drop=True),
        education_flat.reset_index(drop=True)
    ],
    axis=1
)

candidate1_education = education_final[
    education_final["candidate_id"] == "CAND_0000001"
][[
    "candidate_id",
    "institution",
    "degree",
    "field_of_study",
    "start_year",
    "end_year",
    "grade",
    "tier"
]]

display(candidate1_education)

,candidate_id,institution,degree,field_of_study,start_year,end_year,grade,tier
0,CAND_0000001,Lovely Professional University,B.E.,Computer Science,2017,2020,8.24 CGPA,tier_3

In [14]:
certifications_df = df.explode("certifications")

certifications_flat = pd.json_normalize(certifications_df["certifications"])

certifications_final = pd.concat(
    [
        certifications_df[["candidate_id"]].reset_index(drop=True),
        certifications_flat.reset_index(drop=True)
    ],
    axis=1
)


candidate1_certifications = certifications_final[
    certifications_final["candidate_id"] == "CAND_0000001"
]

display(candidate1_certifications)

   candidate_id name issuer  year
0  CAND_0000001  NaN    NaN   NaN

In [15]:
redrob_flat = pd.json_normalize(df["redrob_signals"])

redrob_final = pd.concat(
    [
        df[["candidate_id"]].reset_index(drop=True),
        redrob_flat.reset_index(drop=True)
    ],
    axis=1
)

display(redrob_final.head(1))

,candidate_id,profile_completeness_score,signup_date,last_active_date,open_to_work_flag,profile_views_received_30d,applications_submitted_30d,recruiter_response_rate,avg_response_time_hours,connection_count,endorsements_received,notice_period_days,preferred_work_mode,willing_to_relocate,github_activity_score,search_appearance_30d,saved_by_recruiters_30d,interview_completion_rate,offer_acceptance_rate,verified_email,verified_phone,linkedin_connected,skill_assessment_scores.NLP,skill_assessment_scores.Image Classification,skill_assessment_scores.Fine-tuning LLMs,skill_assessment_scores.Speech Recognition,expected_salary_range_inr_lpa.min,expected_salary_range_inr_lpa.max,skill_assessment_scores.GANs,skill_assessment_scores.OpenCV,skill_assessment_scores.Prompt Engineering,skill_assessment_scores.Object Detection,skill_assessment_scores.Recommendation Systems,skill_assessment_scores.FAISS,skill_assessment_scores.Weights & Biases,skill_assessment_scores.Forecasting,skill_assessment_scores.LangChain,skill_assessment_scores.YOLO,skill_assessment_scores.PEFT,skill_assessment_scores.Data Science,skill_assessment_scores.MLflow,skill_assessment_scores.Pinecone,skill_assessment_scores.Feature Engineering,skill_assessment_scores.BentoML,skill_assessment_scores.MLOps,skill_assessment_scores.Qdrant,skill_assessment_scores.CNN,skill_assessment_scores.Kubeflow,skill_assessment_scores.Machine Learning,skill_assessment_scores.Reinforcement Learning,skill_assessment_scores.Sentence Transformers,skill_assessment_scores.Haystack,skill_assessment_scores.Hugging Face Transformers,skill_assessment_scores.Semantic Search,skill_assessment_scores.LoRA,skill_assessment_scores.Diffusion Models,skill_assessment_scores.Milvus,skill_assessment_scores.Time Series,skill_assessment_scores.Statistical Modeling,skill_assessment_scores.Elasticsearch,skill_assessment_scores.Information Retrieval,skill_assessment_scores.Vector Search,skill_assessment_scores.Learning to Rank,skill_assessment_scores.ASR,skill_assessment_scores.TensorFlow,skill_assessment_scores.LLMs,skill_assessment_scores.Computer Vision,skill_assessment_scores.TTS,skill_assessment_scores.Weaviate,skill_assessment_scores.RAG,skill_assessment_scores.Python,skill_assessment_scores.OpenSearch,skill_assessment_scores.BM25,skill_assessment_scores.scikit-learn,skill_assessment_scores.pgvector,skill_assessment_scores.Embeddings,skill_assessment_scores.LlamaIndex,skill_assessment_scores.PyTorch,skill_assessment_scores.Deep Learning,skill_assessment_scores.QLoRA
0,CAND_0000001,86.9,2025-10-16,2026-05-20,True,23,2,0.34,177.8,356,35,60,onsite,False,9.2,249,4,0.71,0.58,True,True,False,38.8,64.8,41.6,53.7,18.7,36.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
languages_df = df.explode("languages")

languages_flat = pd.json_normalize(languages_df["languages"])

languages_final = pd.concat(
    [
        languages_df[["candidate_id"]].reset_index(drop=True),
        languages_flat.reset_index(drop=True)
    ],
    axis=1
)


candidate1_languages = languages_final[
    languages_final["candidate_id"] == "CAND_0000001"
]

display(candidate1_languages)

   candidate_id language     proficiency
0  CAND_0000001  English    professional
1  CAND_0000001    Hindi  conversational

In [17]:
candidate1_profile = profile_final[
    profile_final["candidate_id"] == "CAND_0000001"
]

display(candidate1_profile.T)

                                                                      0
candidate_id                                               CAND_0000001
anonymized_name                                                Ira Vora
headline                           Backend Engineer | SQL, Spark, Cloud
summary               Software / data professional with 6.9 years of...
location                                                        Toronto
country                                                          Canada
years_of_experience                                                 6.9
current_title                                          Backend Engineer
current_company                                                Mindtree
current_company_size                                             10001+
current_industry                                            IT Services

In [18]:
career_text = "\n\n".join(
    f"{title}: {desc}"
    for title, desc in zip(
        candidate1_career_history["title"],
        candidate1_career_history["description"]
    )
)

print(career_text)

Backend Engineer: Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.

Analytics Engineer: Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.

# Skill score

In [ ]:
Skills

skill_score = (
    0.2 * claimed_skills_match +
    0.3 * assessment_score 
    

)

In [19]:
display(candidate1_skills)

                    name   proficiency  endorsements  duration_months
0               Tailwind  intermediate             3               13
1                    NLP      advanced            37               26
2   Image Classification      advanced             7               40
3       Fine-tuning LLMs      advanced            21               36
4       Weights & Biases  intermediate            13               30
5     Speech Recognition      advanced            52               33
6              Photoshop  intermediate             8               24
7                    TTS      advanced            56               60
8                   LoRA  intermediate             0               28
9            Apache Beam  intermediate             4                9
10                   AWS      beginner             5                8
11                 Flask      beginner            15               15
12               BentoML  intermediate             3               36
13                Milvus      advanced            40               35
14                  GANs      advanced            12               19
15  Statistical Modeling  intermediate             9                8
16                   GCP      beginner             7                2

In [20]:
import numpy as np

proficiency_weights = {
    "beginner": 25,
    "intermediate": 50,
    "advanced": 75,
    "expert": 90
}

def calculate_skill_score(row):
    prof = proficiency_weights.get(
        str(row["proficiency"]).lower(),
        50
    )

    # logarithmic endorsement scaling
    endorsement_score = min(
        np.log1p(row["endorsements"]) / np.log1p(100) * 100,
        100
    )

    # experience saturation at 5 years
    duration_score = min(
        np.log1p(row["duration_months"]) / np.log1p(60) * 100,
        100
    )

    score = (
        0.50 * prof +
        0.20 * endorsement_score +
        0.30 * duration_score
    )

    return round(score, 1)

In [21]:
candidate1_skills["skill_score"] = candidate1_skills.apply(
    calculate_skill_score,
    axis=1
)

display(
    candidate1_skills[
        [
            "name",
          
            "skill_score"
        ]
    ].sort_values(
        "skill_score",
        ascending=False
    )
)

                    name  skill_score
7                    TTS         85.0
5     Speech Recognition         80.4
13                Milvus         79.7
1                    NLP         77.3
3       Fine-tuning LLMs         77.2
2   Image Classification         73.6
14                  GANs         70.5
4       Weights & Biases         61.5
6              Photoshop         58.0
12               BentoML         57.4
15  Statistical Modeling         51.0
0               Tailwind         50.3
8                   LoRA         49.6
9            Apache Beam         48.8
11                 Flask         44.7
10                   AWS         36.3
16                   GCP         29.5

In [23]:
candidate1_redrob = redrob_final[
    redrob_final["candidate_id"] == "CAND_0000001"
]

display(candidate1_redrob.T)

                                                  0
candidate_id                           CAND_0000001
profile_completeness_score                     86.9
signup_date                              2025-10-16
last_active_date                         2026-05-20
open_to_work_flag                              True
...                                             ...
skill_assessment_scores.Embeddings              NaN
skill_assessment_scores.LlamaIndex              NaN
skill_assessment_scores.PyTorch                 NaN
skill_assessment_scores.Deep Learning           NaN
skill_assessment_scores.QLoRA                   NaN

[80 rows x 1 columns]

In [24]:
row = candidate1_redrob.iloc[0]

skills = {
    col.replace("skill_assessment_scores.", ""): row[col]
    for col in candidate1_redrob.columns
    if col.startswith("skill_assessment_scores.")
    and pd.notna(row[col])
}

print(skills)

{'NLP': 38.8, 'Image Classification': 64.8, 'Fine-tuning LLMs': 41.6, 'Speech Recognition': 53.7}

In [25]:

skill_dict = candidate1_skills.set_index("name")["skill_score"].to_dict()
skill_dict

{'Tailwind': 50.3,
 'NLP': 77.3,
 'Image Classification': 73.6,
 'Fine-tuning LLMs': 77.2,
 'Weights & Biases': 61.5,
 'Speech Recognition': 80.4,
 'Photoshop': 58.0,
 'TTS': 85.0,
 'LoRA': 49.6,
 'Apache Beam': 48.8,
 'AWS': 36.3,
 'Flask': 44.7,
 'BentoML': 57.4,
 'Milvus': 79.7,
 'GANs': 70.5,
 'Statistical Modeling': 51.0,
 'GCP': 29.5}

In [26]:
assessment_scores=skills
profile_scores=skill_dict

In [1]:

import numpy as np

proficiency_weights = {
    "beginner": 25,
    "intermediate": 50,
    "advanced": 75,
    "expert": 90
}

def calculate_skill_score(row):
    prof = proficiency_weights.get(
        str(row["proficiency"]).lower(),
        50
    )

    # logarithmic endorsement scaling
    endorsement_score = min(
        np.log1p(row["endorsements"]) / np.log1p(100) * 100,
        100
    )

    # experience saturation at 5 years
    duration_score = min(
        np.log1p(row["duration_months"]) / np.log1p(60) * 100,
        100
    )

    score = (
        0.50 * prof +
        0.20 * endorsement_score +
        0.30 * duration_score
    )

    return round(score, 1)
candidate1_skills["skill_score"] = candidate1_skills.apply(
    calculate_skill_score,
    axis=1
)

display(
    candidate1_skills[
        [
            "name",
          
            "skill_score"
        ]
    ].sort_values(
        "skill_score",
        ascending=False
    )
)
candidate1_redrob = redrob_final[
    redrob_final["candidate_id"] == "CAND_0000001"
]

display(candidate1_redrob.T)

row = candidate1_redrob.iloc[0]

skills = {
    col.replace("skill_assessment_scores.", ""): row[col]
    for col in candidate1_redrob.columns
    if col.startswith("skill_assessment_scores.")
    and pd.notna(row[col])
}

print(skills)
skill_dict = candidate1_skills.set_index("name")["skill_score"].to_dict()
skill_dict
assessment_scores=skills
profile_scores=skill_dict
final_skills = {}

all_skills = set(profile_scores) | set(assessment_scores)

for skill in all_skills:

    profile = profile_scores.get(skill)
    assessment = assessment_scores.get(skill)

    if assessment is not None and profile is not None:

        final_score = round(
            0.4 * profile +
            0.6 * assessment,
            1
        )

        confidence = "high"

    elif assessment is not None:

        final_score = assessment
        confidence = "medium"

    else:

        final_score = profile
        confidence = "low"

    final_skills[skill] = {
        "score": final_score,
        "confidence": confidence,
        "profile_score": profile,
        "assessment_score": assessment
    }
    filtered_skills = {
    skill: details
    for skill, details in final_skills.items()
    if not (details["confidence"] == "low" and details["score"] < 50)
}

NameError: name 'profile_scores' is not defined

In [29]:
  final_skills

{'TTS': {'score': 85.0,
  'confidence': 'low',
  'profile_score': 85.0,
  'assessment_score': None},
 'Photoshop': {'score': 58.0,
  'confidence': 'low',
  'profile_score': 58.0,
  'assessment_score': None},
 'Fine-tuning LLMs': {'score': 55.8,
  'confidence': 'high',
  'profile_score': 77.2,
  'assessment_score': 41.6},
 'BentoML': {'score': 57.4,
  'confidence': 'low',
  'profile_score': 57.4,
  'assessment_score': None},
 'GCP': {'score': 29.5,
  'confidence': 'low',
  'profile_score': 29.5,
  'assessment_score': None},
 'Weights & Biases': {'score': 61.5,
  'confidence': 'low',
  'profile_score': 61.5,
  'assessment_score': None},
 'LoRA': {'score': 49.6,
  'confidence': 'low',
  'profile_score': 49.6,
  'assessment_score': None},
 'Apache Beam': {'score': 48.8,
  'confidence': 'low',
  'profile_score': 48.8,
  'assessment_score': None},
 'Speech Recognition': {'score': 64.4,
  'confidence': 'high',
  'profile_score': 80.4,
  'assessment_score': 53.7},
 'Tailwind': {'score': 50.3,
  'confidence': 'low',
  'profile_score': 50.3,
  'assessment_score': None},
 'Image Classification': {'score': 68.3,
  'confidence': 'high',
  'profile_score': 73.6,
  'assessment_score': 64.8},
 'Milvus': {'score': 79.7,
  'confidence': 'low',
  'profile_score': 79.7,
  'assessment_score': None},
 'AWS': {'score': 36.3,
  'confidence': 'low',
  'profile_score': 36.3,
  'assessment_score': None},
 'GANs': {'score': 70.5,
  'confidence': 'low',
  'profile_score': 70.5,
  'assessment_score': None},
 'Flask': {'score': 44.7,
  'confidence': 'low',
  'profile_score': 44.7,
  'assessment_score': None},
 'Statistical Modeling': {'score': 51.0,
  'confidence': 'low',
  'profile_score': 51.0,
  'assessment_score': None},
 'NLP': {'score': 54.2,
  'confidence': 'high',
  'profile_score': 77.3,
  'assessment_score': 38.8}}

In [37]:
filtered_skills = {
    skill: details
    for skill, details in final_skills.items()
    if not (details["confidence"] == "low" and details["score"] < 50)
}

In [39]:
  filtered_skills

{'TTS': {'score': 85.0,
  'confidence': 'low',
  'profile_score': 85.0,
  'assessment_score': None},
 'Photoshop': {'score': 58.0,
  'confidence': 'low',
  'profile_score': 58.0,
  'assessment_score': None},
 'Fine-tuning LLMs': {'score': 55.8,
  'confidence': 'high',
  'profile_score': 77.2,
  'assessment_score': 41.6},
 'BentoML': {'score': 57.4,
  'confidence': 'low',
  'profile_score': 57.4,
  'assessment_score': None},
 'Weights & Biases': {'score': 61.5,
  'confidence': 'low',
  'profile_score': 61.5,
  'assessment_score': None},
 'Speech Recognition': {'score': 64.4,
  'confidence': 'high',
  'profile_score': 80.4,
  'assessment_score': 53.7},
 'Tailwind': {'score': 50.3,
  'confidence': 'low',
  'profile_score': 50.3,
  'assessment_score': None},
 'Image Classification': {'score': 68.3,
  'confidence': 'high',
  'profile_score': 73.6,
  'assessment_score': 64.8},
 'Milvus': {'score': 79.7,
  'confidence': 'low',
  'profile_score': 79.7,
  'assessment_score': None},
 'GANs': {'score': 70.5,
  'confidence': 'low',
  'profile_score': 70.5,
  'assessment_score': None},
 'Statistical Modeling': {'score': 51.0,
  'confidence': 'low',
  'profile_score': 51.0,
  'assessment_score': None},
 'NLP': {'score': 54.2,
  'confidence': 'high',
  'profile_score': 77.3,
  'assessment_score': 38.8}}

In [30]:
print(career_text)

Backend Engineer: Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.

Analytics Engineer: Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.

In [32]:
display(profile_final.head(1))

,candidate_id,anonymized_name,headline,summary,location,country,years_of_experience,current_title,current_company,current_company_size,current_industry
0,CAND_0000001,Ira Vora,"Backend Engineer | SQL, Spark, Cloud",Software / data professional with 6.9 years of...,Toronto,Canada,6.9,Backend Engineer,Mindtree,10001+,IT Services

In [33]:
profile_final["summary"][0]

"Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice."

In [34]:
profile_final["years_of_experience"][0]

6.9

In [52]:
profile = f"""
Candidate Summary: {profile_final["summary"].iloc[0]}

Candidate YOE: {profile_final["years_of_experience"].iloc[0]}

Career history:
{career_text}

skills scores with confidence high or low: 
{filtered_skills}
"""

print(profile)

Candidate Summary: Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.

Candidate YOE: 6.9

Career history:
Backend Engineer: Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.

Analytics Engineer: Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.

skills scores with confidence high or low:
{'TTS': {'score': 85.0, 'confidence': 'low', 'profile_score': 85.0, 'assessment_score': None}, 'Photoshop': {'score': 58.0, 'confidence': 'low', 'profile_score': 58.0, 'assessment_score': None}, 'Fine-tuning LLMs': {'score': 55.8, 'confidence': 'high', 'profile_score': 77.2, 'assessment_score': 41.6}, 'BentoML': {'score': 57.4, 'confidence': 'low', 'profile_score': 57.4, 'assessment_score': None}, 'Weights & Biases': {'score': 61.5, 'confidence': 'low', 'profile_score': 61.5, 'assessment_score': None}, 'Speech Recognition': {'score': 64.4, 'confidence': 'high', 'profile_score': 80.4, 'assessment_score': 53.7}, 'Tailwind': {'score': 50.3, 'confidence': 'low', 'profile_score': 50.3, 'assessment_score': None}, 'Image Classification': {'score': 68.3, 'confidence': 'high', 'profile_score': 73.6, 'assessment_score': 64.8}, 'Milvus': {'score': 79.7, 'confidence': 'low', 'profile_score': 79.7, 'assessment_score': None}, 'GANs': {'score': 70.5, 'confidence': 'low', 'profile_score': 70.5, 'assessment_score': None}, 'Statistical Modeling': {'score': 51.0, 'confidence': 'low', 'profile_score': 51.0, 'assessment_score': None}, 'NLP': {'score': 54.2, 'confidence': 'high', 'profile_score': 77.3, 'assessment_score': 38.8}}

# Behavioral score

## Redrob signals

In [41]:
skill_cols = [
    col
    for col in candidate1_redrob.columns
    if col.startswith("skill_assessment_scores.")
]

candidate1_redrob = candidate1_redrob.drop(columns=skill_cols)

candidate1_redrob.columns
import pandas as pd
import numpy as np

row = candidate1_redrob.iloc[0]

# -------------------------
# Market Activity Score
# -------------------------

open_to_work_score = 100 if row["open_to_work_flag"] else 0

days_since_active = (
    pd.Timestamp.today().normalize() -
    pd.to_datetime(row["last_active_date"])
).days

last_active_score = max(0, 100 - days_since_active)

recruiter_response_score = row["recruiter_response_rate"] * 100

applications_score = min(
    row["applications_submitted_30d"] * 20,
    100
)

interview_completion_score = (
    row["interview_completion_rate"] * 100
)

market_activity_score = round(
    0.25 * open_to_work_score +
    0.25 * last_active_score +
    0.20 * recruiter_response_score +
    0.15 * applications_score +
    0.15 * interview_completion_score,
    1
)

# -------------------------
# Availability Score
# -------------------------

if row["notice_period_days"] <= 30:
    notice_score = 100
elif row["notice_period_days"] <= 60:
    notice_score = 70
elif row["notice_period_days"] <= 90:
    notice_score = 40
else:
    notice_score = 20

relocate_score = 100 if row["willing_to_relocate"] else 0

availability_score = round(
    0.60 * notice_score +
    0.40 * relocate_score,
    1
)

# -------------------------
# Credibility Score
# -------------------------

github_score = max(
    0,
    min(row["github_activity_score"] * 10, 100)
)

profile_score = row["profile_completeness_score"]

endorsement_score = min(
    np.log1p(row["endorsements_received"]) /
    np.log1p(100) * 100,
    100
)

credibility_score = round(
    0.50 * github_score +
    0.30 * profile_score +
    0.20 * endorsement_score,
    1
)

# -------------------------
# Final Output
# -------------------------

behavioral_summary = {
    "market_activity_score": market_activity_score,
    "availability_score": availability_score,
    "credibility_score": credibility_score
}

print(behavioral_summary)

Index(['candidate_id', 'profile_completeness_score', 'signup_date',
       'last_active_date', 'open_to_work_flag', 'profile_views_received_30d',
       'applications_submitted_30d', 'recruiter_response_rate',
       'avg_response_time_hours', 'connection_count', 'endorsements_received',
       'notice_period_days', 'preferred_work_mode', 'willing_to_relocate',
       'github_activity_score', 'search_appearance_30d',
       'saved_by_recruiters_30d', 'interview_completion_rate',
       'offer_acceptance_rate', 'verified_email', 'verified_phone',
       'linkedin_connected', 'expected_salary_range_inr_lpa.min',
       'expected_salary_range_inr_lpa.max'],
      dtype='object')

market_activity_score = (
    0.25 * open_to_work_score +
    0.25 * last_active_score +
    0.20 * recruiter_response_score +
    0.15 * applications_score +
    0.15 * interview_completion_score
)

availability_score = (
    0.60 * notice_period_score +
    0.40 * relocate_score
)

credibility_score = (
    0.50 * github_score +
    0.30 * profile_completeness_score +
    0.20 * endorsements_score
)

In [46]:
import pandas as pd
import numpy as np

row = candidate1_redrob.iloc[0]

# -------------------------
# Market Activity Score
# -------------------------

open_to_work_score = 100 if row["open_to_work_flag"] else 0

days_since_active = (
    pd.Timestamp.today().normalize() -
    pd.to_datetime(row["last_active_date"])
).days

last_active_score = max(0, 100 - days_since_active)

recruiter_response_score = row["recruiter_response_rate"] * 100

applications_score = min(
    row["applications_submitted_30d"] * 20,
    100
)

interview_completion_score = (
    row["interview_completion_rate"] * 100
)

market_activity_score = round(
    0.25 * open_to_work_score +
    0.25 * last_active_score +
    0.20 * recruiter_response_score +
    0.15 * applications_score +
    0.15 * interview_completion_score,
    1
)

# -------------------------
# Availability Score
# -------------------------

if row["notice_period_days"] <= 30:
    notice_score = 100
elif row["notice_period_days"] <= 60:
    notice_score = 70
elif row["notice_period_days"] <= 90:
    notice_score = 40
else:
    notice_score = 20

relocate_score = 100 if row["willing_to_relocate"] else 0

availability_score = round(
    0.60 * notice_score +
    0.40 * relocate_score,
    1
)

# -------------------------
# Credibility Score
# -------------------------

github_score = max(
    0,
    min(row["github_activity_score"] * 10, 100)
)

profile_score = row["profile_completeness_score"]

endorsement_score = min(
    np.log1p(row["endorsements_received"]) /
    np.log1p(100) * 100,
    100
)

credibility_score = round(
    0.50 * github_score +
    0.30 * profile_score +
    0.20 * endorsement_score,
    1
)

# -------------------------
# Final Output
# -------------------------

behavioral_summary = {
    "market_activity_score": market_activity_score,
    "availability_score": availability_score,
    "credibility_score": credibility_score
}

print(behavioral_summary)

{'market_activity_score': 66.2, 'availability_score': 42.0, 'credibility_score': 87.6}

In [53]:
profile=profile+"\n"+"behavioral_summary: \n"+str(behavioral_summary)

# Candidate Profile

In [54]:
print(profile)

Candidate Summary: Software / data professional with 6.9 years of experience building data pipelines, backend systems, and analytics infrastructure. I'm a backend/data hybrid — Spark, Airflow, SQL warehouses are home territory; I'm building competence on the ML side. My toolkit is solid on the data engineering side — Python, SQL, Spark, Airflow, warehouse design — and I've completed a couple of self-directed ML projects (Kaggle competitions, side projects fine-tuning small models). Interested in transitioning toward more AI/ML-focused work, ideally at a company where I can leverage my existing data-infra skills while learning modern ML practice.

Candidate YOE: 6.9

Career history:
Backend Engineer: Implemented streaming data pipelines on Kafka and Spark Streaming for a real-time user-activity processing platform. Designed the schema-registry integration, the watermark/state management approach, and the deduplication logic for late-arriving events. Worked closely with the data science team to make sure feature pipelines aligned with what their models needed. Most of my career has been data engineering, with some adjacent ML exposure.

Analytics Engineer: Built and maintained data pipelines on Apache Airflow processing ~500GB of daily transactional data across 12 source systems. Worked extensively with Spark (PySpark) for batch processing and dbt for the transformation/modeling layer in our Snowflake warehouse. Owned the on-call rotation for data quality issues — wrote most of the data quality checks that detect schema drift and unusual volume changes. The pipeline supports the analytics team and a few internal ML models.

skills scores with confidence high or low:
{'TTS': {'score': 85.0, 'confidence': 'low', 'profile_score': 85.0, 'assessment_score': None}, 'Photoshop': {'score': 58.0, 'confidence': 'low', 'profile_score': 58.0, 'assessment_score': None}, 'Fine-tuning LLMs': {'score': 55.8, 'confidence': 'high', 'profile_score': 77.2, 'assessment_score': 41.6}, 'BentoML': {'score': 57.4, 'confidence': 'low', 'profile_score': 57.4, 'assessment_score': None}, 'Weights & Biases': {'score': 61.5, 'confidence': 'low', 'profile_score': 61.5, 'assessment_score': None}, 'Speech Recognition': {'score': 64.4, 'confidence': 'high', 'profile_score': 80.4, 'assessment_score': 53.7}, 'Tailwind': {'score': 50.3, 'confidence': 'low', 'profile_score': 50.3, 'assessment_score': None}, 'Image Classification': {'score': 68.3, 'confidence': 'high', 'profile_score': 73.6, 'assessment_score': 64.8}, 'Milvus': {'score': 79.7, 'confidence': 'low', 'profile_score': 79.7, 'assessment_score': None}, 'GANs': {'score': 70.5, 'confidence': 'low', 'profile_score': 70.5, 'assessment_score': None}, 'Statistical Modeling': {'score': 51.0, 'confidence': 'low', 'profile_score': 51.0, 'assessment_score': None}, 'NLP': {'score': 54.2, 'confidence': 'high', 'profile_score': 77.3, 'assessment_score': 38.8}}

behavioral_summary:
{'market_activity_score': 66.2, 'availability_score': 42.0, 'credibility_score': 87.6}

# Match Score

In [58]:
import json
import google.generativeai as genai

genai.configure(api_key="AQ.Ab8RN6KmD4TTFg3t6taJ1oY3k14VFjr5-4ccWVQvnVl_ESWBtA")

model = genai.GenerativeModel("gemini-3.5-flash")



prompt = f"""
You are an expert technical recruiter.

JOB DESCRIPTION:
{job_profile}

CANDIDATE Profile:
{profile}

Evaluate the candidate against the job.

For each scoring dimension:

1. Give score 0-100 (take into account only the relevent skill scores along with the behaviorial scores and candidates career history)
2. Cite evidence from candidate profile
3. Cite missing evidence
4. Give confidence, see if there is  any inconsistancy or iumpossibilty as it could be a honeypot profile

Then compute:

overall_score =
weighted average using scoring_dimensions weights.
Final_Verdict
Return JSON only.
  

"""

response = model.generate_content(prompt)

print(response.text)

```json
{
  "scoring_dimensions": [
    {
      "name": "Production Ranking & Retrieval Experience",
      "score": 10,
      "evidence_present": "None in their professional career history. The candidate is a backend/data hybrid whose actual work has centered entirely on Spark, Kafka, Airflow, and Snowflake pipelines.",
      "missing_evidence": "No production experience with embedding-based retrieval models, vector database lifecycle management (index refresh, handling drift), or hybrid search engine implementation. While 'Milvus' is listed in their skills with a low-confidence score of 79.7, there is absolutely zero evidence of its application in their professional history.",
      "confidence": "high",
      "notes": "The candidate explicitly states they are 'building competence on the ML side' and looking to transition toward AI/ML, confirming they do not currently have production search or retrieval experience."
    },
    {
      "name": "Production-Grade Coding & Architecture (Python)",
      "score": 75,
      "evidence_present": "Demonstrated strong backend and data engineering capability. Experienced in implementing streaming pipelines (Kafka, Spark Streaming) and batch workflows (Airflow, PySpark, Snowflake, dbt). They understand schema registries, state management, and deduplication logic.",
      "missing_evidence": "Lacks experience architecting low-latency model inference systems, production ML serving pipelines, or real-time vector retrieval architectures.",
      "confidence": "high",
      "notes": "While their Python/data coding is production-grade, it is currently constrained to the data-platform domain rather than machine learning or search systems."
    },
    {
      "name": "Evaluation Rigor & Metrics",
      "score": 20,
      "evidence_present": "Wrote data quality checks to detect schema drift and unusual volume changes for transactional data pipelines.",
      "missing_evidence": "Zero evidence of working with Information Retrieval (IR) evaluation metrics such as NDCG, MRR, or MAP. No experience designing offline-to-online evaluation loops or search-specific A/B testing infrastructure.",
      "confidence": "high",
      "notes": "Their understanding of 'evaluation' is strictly from a data-governance/quality standpoint, not ML model performance or search relevance tuning."
    },
    {
      "name": "Product Startup Shipper Mindset",
      "score": 40,
      "evidence_present": "Managed on-call rotations, dealt with chaotic raw data sources, and designed pragmatically to support downstream analytics and internal models.",
      "missing_evidence": "Lacks the ability to independently design, deploy, and scale high-leverage ML systems. They are looking for a role where they can 'learn modern ML practice,' which runs counter to the founding engineer requirement of being immediately self-sufficient without support infra.",
      "confidence": "high",
      "notes": "They have a shipper mindset for pipelines, but are a complete beginner in shipping production AI/ML systems."
    }
  ],
  "overall_score": 34.25,
  "final_verdict": {
    "decision": "Strong Reject",
    "reasoning": "The candidate is a highly capable Data/Backend Engineer, but a complete mismatch for a Senior Founding AI Engineer role. They have zero production-scale ranking, search, recommendation, or NLP experience. They do not fit the 'Product-Minded ML Shipper' archetype; instead, they fit a transitional data engineer profile looking to learn ML on the job. The JD demands immediate ownership of v2 search engines using NDCG/MRR metrics and vector databases from day one, which this candidate cannot deliver without extensive training."
  }
}
```